# Generated by Django 2.2.16 on 2020-10-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NW', 'New'), ('PL', 'Planned'), ('IW', 'In work'), ('FS', 'Finished')], max_length=40)),
                ('expected_dead_line', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
