# Generated by Django 2.2.16 on 2020-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20201007_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In_work', 'In work'), ('Finished', 'Finished')], max_length=40),
        ),
    ]
